<?xml version="1.0" encoding="utf-8"?><Database Name="PHUKIENANIME" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HUNTER95LAPTOP;Initial Catalog=PHUKIENANIME;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PHUKIENANIMEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Banner" Member="Banners">
    <Type Name="Banner">
      <Column Name="Banner" Member="Banner1" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTIN" Member="THONGTINs">
    <Type Name="THONGTIN">
      <Column Name="Tencuahang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Sdt1" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="sdt2" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="Email1" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Email2" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="Char(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_DDH" Member="CT_DDHs">
    <Type Name="CT_DDH">
      <Column Name="Idsp" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHD" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="DONDATHANG_CT_DDH" Member="DONDATHANG" ThisKey="SoHD" OtherKey="SoHD" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_CT_DDH" Member="SANPHAM" ThisKey="Idsp" OtherKey="Idsp" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_GIOHANG" Member="CT_GIOHANGs">
    <Type Name="CT_GIOHANG">
      <Column Name="Idsp" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sogh" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Char(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Thanhtien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="GIOHANG_CT_GIOHANG" Member="GIOHANG" ThisKey="Sogh,Username" OtherKey="Sogh,Username" Type="GIOHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_CT_GIOHANG" Member="SANPHAM" ThisKey="Idsp" OtherKey="Idsp" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_PN" Member="CT_PNs">
    <Type Name="CT_PN">
      <Column Name="Idsp" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoPN" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Giatien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="PHIEUNHAP_CT_PN" Member="PHIEUNHAP" ThisKey="SoPN" OtherKey="SoPN" Type="PHIEUNHAP" IsForeignKey="true" />
      <Association Name="SANPHAM_CT_PN" Member="SANPHAM" ThisKey="Idsp" OtherKey="Idsp" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="SoHD" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Ngaylap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Tongtien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Ngaythanhtoan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DONDATHANG_CT_DDH" Member="CT_DDHs" ThisKey="SoHD" OtherKey="SoHD" Type="CT_DDH" />
      <Association Name="KHACHHANG_DONDATHANG" Member="KHACHHANG" ThisKey="Username" OtherKey="Username" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOHANG" Member="GIOHANGs">
    <Type Name="GIOHANG">
      <Column Name="Sogh" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Char(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GIOHANG_CT_GIOHANG" Member="CT_GIOHANGs" ThisKey="Sogh,Username" OtherKey="Sogh,Username" Type="CT_GIOHANG" />
      <Association Name="KHACHHANG_GIOHANG" Member="KHACHHANG" ThisKey="Username" OtherKey="Username" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="Username" Type="System.String" DbType="Char(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Sdt" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_DONDATHANG" Member="DONDATHANGs" ThisKey="Username" OtherKey="Username" Type="DONDATHANG" />
      <Association Name="KHACHHANG_GIOHANG" Member="GIOHANGs" ThisKey="Username" OtherKey="Username" Type="GIOHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="Idloai" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenloai" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="SANPHAMs" ThisKey="Idloai" OtherKey="Idloai" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHASANXUAT" Member="NHASANXUATs">
    <Type Name="NHASANXUAT">
      <Column Name="Idnsx" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tennsx" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Association Name="NHASANXUAT_SANPHAM" Member="SANPHAMs" ThisKey="Idnsx" OtherKey="Idnsx" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="SoPN" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngaylap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Tongchi" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CT_PN" Member="CT_PNs" ThisKey="SoPN" OtherKey="SoPN" Type="CT_PN" />
    </Type>
  </Table>
  <Table Name="dbo.QUANTRI" Member="QUANTRIs">
    <Type Name="QUANTRI">
      <Column Name="[User]" Member="User" Type="System.String" DbType="Char(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="Idsp" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Idnsx" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Idloai" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Tensanpham" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Thongtin" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Soluongcon" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Hinhanh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SANPHAM_CT_DDH" Member="CT_DDHs" ThisKey="Idsp" OtherKey="Idsp" Type="CT_DDH" />
      <Association Name="SANPHAM_CT_GIOHANG" Member="CT_GIOHANGs" ThisKey="Idsp" OtherKey="Idsp" Type="CT_GIOHANG" />
      <Association Name="SANPHAM_CT_PN" Member="CT_PNs" ThisKey="Idsp" OtherKey="Idsp" Type="CT_PN" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="LOAISANPHAM" ThisKey="Idloai" OtherKey="Idloai" Type="LOAISANPHAM" IsForeignKey="true" />
      <Association Name="NHASANXUAT_SANPHAM" Member="NHASANXUAT" ThisKey="Idnsx" OtherKey="Idnsx" Type="NHASANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>